---
  - name: "upgrade packages."
    become: true
    apt:
      upgrade: "yes"


  - name: Install node, npm
    become: true
    command: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
      sudo apt-get install -y nodejs

  - name: Install pm2
    become: true
    command: npm install pm2 -g