---
  - name: Copy artifact
    copy:
      src:  artifact.tar.gz
      dest: ~/artifact.tar.gz
  - name: Extract tar file
    shell: |
      mkdir backend
      tar -xvf artifact.tar.gz -C backend
  - name: Install 
    shell: |
      cd backend
      npm install
      pm2 stop default
      pm2 start npm -- start
