---
  - name: Copy artifact
    copy:
      src:  artifact
      dest: ~/artifact
  - name: Extract tar file
    shell: |
      tar -xzvf artifact
  - name: Install 
    shell: |
      cd artifact
      npm install
      pm2 stop default
      pm2 start npm -- start
