version: 2.1

jobs:
  build-frontend:
    docker: 
        - image: node:14
    steps:
      - checkout
      - run: 
          name: Build frontend
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths:
            - "frontend/node_modules"
          key: frontend-build

  test-frontend:
    docker: 
        - image: node:14
    steps:
      - checkout
      - restore_cache:
          key: frontend-build
      - run:
          name: Test Frontend
          command: |
            cd frontend
            npm install
            npm run test

  scan-frontend:
    docker:
      - image: node:14
    steps:
      - checkout
      - restore_cache:
          key: frontend-build
      - run:
          name: Scan frontend
          command: |
            cd frontend
            npm install
            npm audit --audit-level=critical

  build-backend:
    docker: 
        - image: node:14
    steps:
      - checkout
      - run: 
          name: Build Backend
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths:
            - "backend/node_modules"
          key: backend-build

  test-backend:
    docker: 
        - image: node:14
    steps:
      - checkout
      - restore_cache:
          key: backend-build
      - run: 
          name: Test Backend
          command: |
            cd backend
            npm install
            npm run test
      
  scan-backend:
    docker:
      - image: node:14
    steps:
      - checkout
      - restore_cache:
          key: backend-build
      - run:
          name: Scan backend
          command: |
            cd backend
            npm install
            npm audit --audit-level=critical
workflows:
  dev:
    jobs:
      - build-backend
      - build-frontend
      - test-frontend:
          requires:
            - build-frontend
      - test-backend:
          requires:
            - build-backend
      - scan-backend:
          requires:
            - test-backend
      - scan-frontend:
          requires:
            - test-frontend